### ISSUE TITLE
API Throttle

### ISSUE THREAD

**Issue by thomasdavis** [nfriedly/node-pagerank#1]
Hey there, cool plugin and it works well. Looking at doing it for a bulk set of records. Do you have any insight on how often you could ping without getting ip banned?

**Comment by nfriedly** [comment]
No, I've never done enough hits for Google to ban me. 30 within a few seconds defiantly OK, 100 probably is. Not sure how high you can go. Maybe spin up a free Heroku instance and see how far it can go?

**Comment by thomasdavis** [comment]
No worries, I will give it a shot and update you with what I find out.
ᐧ

On Sat, Jan 25, 2014 at 1:07 PM, Nathan Friedly notifications@github.comwrote:

> doh, wait, I was thinking of a different project :/
> 
> No, I've never done enough hits for Google to ban me.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nfriedly/node-pagerank/issues/1#issuecomment-33279599
> .

## 

Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com

**Comment by thomasdavis** [comment]
Just parsed 2300 domains at 1 per second, finished in under an hour without
any hiccups. Thanks for the lib!
ᐧ

On Sat, Jan 25, 2014 at 1:18 PM, Thomas Davis thomasalwyndavis@gmail.comwrote:

> No worries, I will give it a shot and update you with what I find out.
> ᐧ
> 
> On Sat, Jan 25, 2014 at 1:07 PM, Nathan Friedly notifications@github.comwrote:
> 
> > doh, wait, I was thinking of a different project :/
> > 
> > No, I've never done enough hits for Google to ban me.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/nfriedly/node-pagerank/issues/1#issuecomment-33279599
> > .
> 
> ## 
> 
> Thomas Davis
> http://thomasdav.is
> 
> VP of Tech - Earbits - http://earbits.com
> Co-founder - Cdnjs - http://cdnjs.com
> Founder - Backbone Tutorials - http://backbonetutorials.com

## 

Thomas Davis
http://thomasdav.is

VP of Tech - Earbits - http://earbits.com
Co-founder - Cdnjs - http://cdnjs.com
Founder - Backbone Tutorials - http://backbonetutorials.com

**Comment by nfriedly** [comment]
Awesome!

Thanks,
- Nathan
