### ISSUE TITLE
Error with some urls

### ISSUE THREAD

**Issue by teawithfruit** [nfriedly/node-pagerank#2]
Hey,
Thank you for building this module.

The reason why I'm writing this issue is, that some urls (for example http://www.renault.de) won't get thru.
I get this error:
`{ [Error: connect ETIMEDOUT] code: 'ETIMEDOUT', errno: 'ETIMEDOUT', syscall: 'connect' }`

If I'm testing these urls with your example page, there is no problem. Is there something that I have to consider by using your module?

Thanks.

**Comment by nfriedly** [comment]
Which example page? Can you show me your code?

Also, is the computer/server that you're running on able to connect to those urls directly? (e.g., what does the command `ping www.renault.de` do on your server?)
