### ISSUE TITLE
Not working anymore, results 0 for every result

### ISSUE THREAD

**Issue by zthomas** [nfriedly/node-pagerank#4]
Looks like this no longer works? The library returns 0 for every url that I gave it. 

Also the demo on http://pagerank.nfriedly.com/ has the same behaviour. 

Maybe the endpoint has changed?

**Comment by nfriedly** [comment]
No, google announced a while back that they were going to shut down public
access to PageRank, it sounds like that finally happened. I'll publish an
update to make this more clear.
